import React, { useState, useEffect } from 'react';
import { useFormik } from 'formik';
import * as Yup from 'yup';
import { AlertCircle, Loader2, User, Phone, Mail, FileText, MapPin, CreditCard, Hash } from 'lucide-react';

import authenticatedFetch from '../utils/api'; 

const API_BASE_URL = 'https://construction-backend-uwd8.onrender.com/api'; 

const ProjectClientForm = ({ client, onClose, onSaveSuccess }) => {
    const [loading, setLoading] = useState(false);
    const [serverError, setServerError] = useState(null);
    const [successMessage, setSuccessMessage] = useState(null);
    const [selectedFile, setSelectedFile] = useState(null);
    const [nextClientId, setNextClientId] = useState('Loading...');

    // Validation Schema
    const validationSchema = Yup.object({
        clientName: Yup.string().required('Client name is required'),
        phoneNumber: Yup.string()
            .matches(/^[0-9]+$/, 'Phone number should contain only digits')
            .min(10, 'Phone number should be at least 10 digits')
            .max(15, 'Phone number should not exceed 15 digits')
            .required('Phone number is required'),
        gstNo: Yup.string().max(16, 'GST number should not exceed 16 characters'),
        email: Yup.string().email('Invalid email address'), 
        address: Yup.string(),
        description: Yup.string(),
    });

    const formik = useFormik({
        initialValues: {
            clientId: client?.clientId || '', 
            clientName: client?.clientName || '',
            phoneNumber: client?.phoneNumber || '',
            gstNo: client?.gstNo || '',
            email: client?.email || '',
            address: client?.address || '',
            description: client?.description || '',
        },
        validationSchema,
        enableReinitialize: true, 
        onSubmit: async (values) => {
            setLoading(true);
            setServerError(null);
            setSuccessMessage(null);

            const formData = new FormData();
            // clientId is usually auto-generated by backend logic, sending it is optional but good for consistency if needed
            // formData.append('clientId', values.clientId); 

            formData.append('clientId', values.clientId);
            formData.append('clientName', values.clientName);
            formData.append('phoneNumber', values.phoneNumber);
            formData.append('gstNo', values.gstNo);
            formData.append('email', values.email);
            formData.append('address', values.address);
            formData.append('description', values.description);
            
            if (selectedFile) {
                formData.append('photo', selectedFile);
            }

            const isEditing = !!client?._id;
            const method = isEditing ? 'PUT' : 'POST';

            const endpoint = isEditing
                ? `/clients/${client._id}`
                : `/clients`;

            try {
                const response = await authenticatedFetch(endpoint, {
                    method,
                    body: formData,
                });

                if (!response.ok) {
                    const errorData = await response.json().catch(() => ({ message: 'Client details could not be saved.' }));
                    throw new Error(errorData.message || 'Client details could not be saved.');
                }

                setSuccessMessage(isEditing ? "Client updated successfully!" : "Client added successfully!");
                
                setTimeout(() => {
                    if (onSaveSuccess) onSaveSuccess();
                    onClose();
                }, 1500);

            } catch (err) {
                console.error("API Error:", err);
                setServerError(err.message || "Client details could not be saved.");
            } finally {
                setLoading(false);
            }
        },
    });

    // Fetch Next Client ID (Only for New Client)
    useEffect(() => {
        let isMounted = true; // To prevent state updates on unmounted component

        if (!client) {
            const fetchNextId = async () => {
                try {
                    const token = localStorage.getItem('token');
                    // Corrected URL: using API_BASE_URL explicitly for this fetch
                    const response = await fetch(`${API_BASE_URL}/clients/next-id`, {
                        headers: { 'Authorization': `Bearer ${token}` }
                    });
                    
                    if (response.ok) {
                        const data = await response.json();
                        if (isMounted) {
                            setNextClientId(data.clientId);
                            formik.setFieldValue('clientId', data.clientId);
                        }
                    } else {
                         if (isMounted) setNextClientId('Error');
                    }
                } catch (error) {
                    console.error("Error fetching next client ID:", error);
                    if (isMounted) setNextClientId('Error');
                }
            };
            fetchNextId();
        } else {
            if (isMounted) {
                setNextClientId(client.clientId || 'N/A');
                formik.setFieldValue('clientId', client.clientId);
            }
        }

        return () => {
            isMounted = false; // Cleanup function
        };
    }, [client]); 

    const handleFileChange = (event) => {
        const file = event.currentTarget.files[0];
        setSelectedFile(file);
    };

    return (
        <div className="bg-white p-6 rounded-xl shadow-2xl max-w-lg mx-auto border-t-4 border-indigo-600">
            <h2 className="text-2xl font-bold mb-6 text-gray-800 flex items-center">
                <User className="w-6 h-6 mr-2 text-indigo-600" />
                {client ? 'Update Client Details' : 'Add New Client'}
            </h2>
            
            <form onSubmit={formik.handleSubmit} className="space-y-4">
                
                {/* Client ID (Read Only) */}
                <div className="form-group">
                    <label htmlFor="clientId" className="block text-sm font-semibold text-gray-700 mb-1">
                        Client ID <span className="text-gray-400 font-normal">(Auto)</span>
                    </label>
                    <div className="relative">
                        <Hash className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400 w-4 h-4" />
                        <input
                            type="text"
                            id="clientId"
                            value={nextClientId} 
                            readOnly 
                            disabled 
                            className="w-full pl-10 pr-3 py-2 border border-gray-300 rounded-lg bg-gray-100 text-gray-500 cursor-not-allowed focus:outline-none"
                        />
                    </div>
                </div>

                {/* Name & Phone Row */}
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div>
                        <label htmlFor="clientName" className="block text-sm font-semibold text-gray-700 mb-1">
                            Client Name <span className="text-red-500">*</span>
                        </label>
                        <div className="relative">
                            <User className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400 w-4 h-4" />
                            <input
                                type="text"
                                id="clientName"
                                {...formik.getFieldProps('clientName')}
                                className={`w-full pl-10 pr-3 py-2 border rounded-lg focus:outline-none focus:ring-2 transition-colors ${formik.touched.clientName && formik.errors.clientName ? 'border-red-500 focus:ring-red-200' : 'border-gray-300 focus:ring-indigo-200'}`}
                                placeholder="Enter name"
                            />
                        </div>
                        {formik.touched.clientName && formik.errors.clientName && (
                            <p className="mt-1 text-xs text-red-500">{formik.errors.clientName}</p>
                        )}
                    </div>

                    <div>
                        <label htmlFor="phoneNumber" className="block text-sm font-semibold text-gray-700 mb-1">
                            Phone Number <span className="text-red-500">*</span>
                        </label>
                        <div className="relative">
                            <Phone className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400 w-4 h-4" />
                            <input
                                type="text"
                                id="phoneNumber"
                                {...formik.getFieldProps('phoneNumber')}
                                className={`w-full pl-10 pr-3 py-2 border rounded-lg focus:outline-none focus:ring-2 transition-colors ${formik.touched.phoneNumber && formik.errors.phoneNumber ? 'border-red-500 focus:ring-red-200' : 'border-gray-300 focus:ring-indigo-200'}`}
                                placeholder="9876543210"
                            />
                        </div>
                        {formik.touched.phoneNumber && formik.errors.phoneNumber && (
                            <p className="mt-1 text-xs text-red-500">{formik.errors.phoneNumber}</p>
                        )}
                    </div>
                </div>

                {/* GST & Email Row */}
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div>
                        <label htmlFor="gstNo" className="block text-sm font-semibold text-gray-700 mb-1">GST No</label>
                        <div className="relative">
                            <CreditCard className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400 w-4 h-4" />
                            <input
                                type="text"
                                id="gstNo"
                                {...formik.getFieldProps('gstNo')}
                                className="w-full pl-10 pr-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-indigo-200 transition-colors"
                                placeholder="Optional"
                            />
                        </div>
                        {formik.touched.gstNo && formik.errors.gstNo && (
                            <p className="mt-1 text-xs text-red-500">{formik.errors.gstNo}</p>
                        )}
                    </div>

                    <div>
                        <label htmlFor="email" className="block text-sm font-semibold text-gray-700 mb-1">Email</label>
                        <div className="relative">
                            <Mail className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400 w-4 h-4" />
                            <input
                                type="email"
                                id="email"
                                {...formik.getFieldProps('email')}
                                className={`w-full pl-10 pr-3 py-2 border rounded-lg focus:outline-none focus:ring-2 transition-colors ${formik.touched.email && formik.errors.email ? 'border-red-500 focus:ring-red-200' : 'border-gray-300 focus:ring-indigo-200'}`}
                                placeholder="Optional"
                            />
                        </div>
                        {formik.touched.email && formik.errors.email && (
                            <p className="mt-1 text-xs text-red-500">{formik.errors.email}</p>
                        )}
                    </div>
                </div>

                {/* Photo Upload */}
                <div>
                    <label htmlFor="photo" className="block text-sm font-semibold text-gray-700 mb-1">Photo</label>
                    <input
                        type="file"
                        id="photo"
                        name="photo"
                        className="w-full text-sm text-gray-500 file:mr-4 file:py-2 file:px-4 file:rounded-full file:border-0 file:text-sm file:font-semibold file:bg-indigo-50 file:text-indigo-700 hover:file:bg-indigo-100 cursor-pointer"
                        onChange={handleFileChange}
                    />
                    {selectedFile && (
                        <p className="mt-1 text-xs text-green-600">Selected: {selectedFile.name}</p>
                    )}
                </div>

                {/* Address */}
                <div>
                    <label htmlFor="address" className="block text-sm font-semibold text-gray-700 mb-1">Address</label>
                    <div className="relative">
                        <MapPin className="absolute left-3 top-3 text-gray-400 w-4 h-4" />
                        <textarea
                            id="address"
                            {...formik.getFieldProps('address')}
                            rows="2"
                            className="w-full pl-10 pr-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-indigo-200 transition-colors resize-none"
                            placeholder="Client Address"
                        />
                    </div>
                </div>

                {/* Description */}
                <div>
                    <label htmlFor="description" className="block text-sm font-semibold text-gray-700 mb-1">Description</label>
                    <div className="relative">
                        <FileText className="absolute left-3 top-3 text-gray-400 w-4 h-4" />
                        <textarea
                            id="description"
                            {...formik.getFieldProps('description')}
                            rows="2"
                            className="w-full pl-10 pr-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-indigo-200 transition-colors resize-none"
                            placeholder="Additional notes"
                        />
                    </div>
                </div>

                {/* Messages */}
                {loading && (
                    <div className="flex items-center justify-center text-indigo-600 space-x-2 bg-indigo-50 p-2 rounded-lg">
                        <Loader2 className="h-5 w-5 animate-spin" />
                        <span className="text-sm font-medium">Processing...</span>
                    </div>
                )}
                {serverError && (
                    <div className="bg-red-100 border border-red-400 text-red-700 px-4 py-2 rounded-lg flex items-center space-x-2 text-sm">
                        <AlertCircle className="h-4 w-4 flex-shrink-0" />
                        <span>{serverError}</span>
                    </div>
                )}
                {successMessage && (
                    <div className="bg-green-100 border border-green-400 text-green-700 px-4 py-2 rounded-lg text-center text-sm font-medium">
                        {successMessage}
                    </div>
                )}

                {/* Actions */}
                <div className="flex justify-end space-x-3 pt-4 border-t">
                    <button
                        type="button"
                        onClick={onClose}
                        className="px-5 py-2 bg-gray-100 text-gray-700 rounded-lg hover:bg-gray-200 font-medium transition-colors"
                        disabled={loading}
                    >
                        Cancel
                    </button>
                    <button
                        type="submit"
                        className="px-5 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 font-medium shadow-md hover:shadow-lg transition-all disabled:bg-indigo-400"
                        disabled={loading}
                    >
                        {client ? 'Update Client' : 'Save Client'}
                    </button>
                </div>
            </form>
        </div>
    );
};

export default ProjectClientForm;